ERROR Traceback (most recent call last):
  File "C:\Documents and Settings\geostaff\Desktop\PostGIS\sshPostGIS.py", line 486, in main
    export_layer(db_info, gs_info, data_info, featLayer)
  File "C:\Documents and Settings\geostaff\Desktop\PostGIS\sshPostGIS.py", line 429, in export_layer
    with closing(createConnObj(db_info._replace(database='postgres'))) as cxn:
  File "C:\Documents and Settings\geostaff\Desktop\PostGIS\sshPostGIS.py", line 240, in createConnObj
    connxion = psycopg2.connect(**db_info._asdict())
OperationalError: FATAL:  password authentication failed for user "anything"
FATAL:  password authentication failed for user "anything"
